name: Python Unit Test

# 언제 실행할지 정의 (main 브랜치에 push되거나 PR이 올 때)
on:
  push:
    branches: [ "main" ] # "master"를 쓴다면 여기를 수정하세요
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # 우분투 최신 환경에서 실행

    steps:
    # 1. GitHub 저장소의 코드를 내려받음
    - uses: actions/checkout@v3

    # 2. 파이썬 설치 및 버전 설정
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10" # 프로젝트에 맞는 버전으로 변경 가능

    # 3. 의존성 패키지 설치
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
        pip install -r requirements.txt;

    # 4. pytest 실행
    - name: Test with pytest
      run: |
        pytest --cov=src --cov-report=xml --cov-report=term-missing --cov-fail-under=80 tests/
        pytest -v tests/test_infra_notifier_live.py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: true

    - name: Slack Notification on Failure
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        author_name: GitHub Actions Test Fail
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # 아까 등록한 시크릿 사용
      if: failure() # 중요: 앞 단계가 실패했을 때만 실행됨